# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "fb616a8f-8cc4-4f56-b01f-42e333b4962d",
# META       "default_lakehouse_name": "SAMPLE_LH_TEST",
# META       "default_lakehouse_workspace_id": "4e8e7839-ec41-443b-b407-917690635626",
# META       "known_lakehouses": [
# META         {
# META           "id": "fb616a8f-8cc4-4f56-b01f-42e333b4962d"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Welcome to your new notebook
# Type here in the cell editor to add code!
!pip install kaggle

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

import os
os.chdir('/lakehouse/default/Files')
os.environ['KAGGLE_USERNAME'] = 'cheekylover2004'
os.environ['KAGGLE_KEY'] = 'KGAT_2325276173e5af610a91a3354c1c9dc6'
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()
api.dataset_download_file('mrsimple07/restaurants-revenue-prediction', 'Restaurant_revenue (1).csv')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

import pandas as pd

df = pd.read_csv('/lakehouse/default/' + 'Files/Restaurant_revenue%20(1).csv')
df.head()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Select column: 'Cuisine_Type'
    df = df.loc[:, ['Cuisine_Type']]
    # Drop duplicate rows across all columns
    df = df.drop_duplicates()
    return df

df_clean = clean_data(df.copy())

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df_clean.head()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df_clean.reset_index(drop=True,inplace=True)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df_clean.head()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df_clean['CuisineTypeID'] = range(0, 0+len(df_clean))

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df_clean.head()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

fact = df.merge(df_clean, on='Cuisine_Type', how='left')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

fact.head()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for pandas DataFrame

def clean_data(fact):
    # Drop column: 'Cuisine_Type'
    fact = fact.drop(columns=['Cuisine_Type'])
    return fact

fact = clean_data(fact.copy())
fact.head()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for pandas DataFrame

def clean_data(fact):
    # Drop columns: 'Number_of_Customers', 'Menu_Price' and 5 other columns
    fact = fact.drop(columns=['Number_of_Customers', 'Menu_Price', 'Marketing_Spend', 'Average_Customer_Spending', 'Reviews', 'Monthly_Revenue', 'CuisineTypeID'])
    # Drop duplicate rows across all columns
    fact = fact.drop_duplicates()
    return fact

prom = clean_data(fact.copy())
prom.head()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

prom['PromotionName'] = prom['Promotions'].map({0:'No', 1:'Yes'})

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

prom.head()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

sparkdfcuisine = spark.createDataFrame(df_clean)
display(sparkdfcuisine)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

sparkdffact = spark.createDataFrame(fact)
sparkdfprom = spark.createDataFrame(prom)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

sparkdfcuisine.write.format('delta').mode('overwrite').saveAsTable('DimCuisineType')
sparkdffact.write.format('delta').mode('overwrite').saveAsTable('FactRestaurant')
sparkdfprom.write.format('delta').mode('overwrite').saveAsTable('DimPromotions')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

sparkdf = spark.createDataFrame(df)
display(sparkdf)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

sparkdf.write.format('delta').mode('overwrite').saveAsTable('sales_raw')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
